name: Build and Test ASP.NET Core Project
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET environment
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0  # Specify your .NET Core version

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    # Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
